import {
    SHOPIFY_CUSTOMER_ACCOUNT_AUTH_ENDPOINT,
    SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID,
    SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET,
    SHOPIFY_CUSTOMER_ACCOUNT_LOGOUT_ENDPOINT,
    SHOPIFY_CUSTOMER_ACCOUNT_REDIRECT_URI,
    SHOPIFY_CUSTOMER_ACCOUNT_TOKEN_ENDPOINT
} from 'lib/constants';
import { NextResponse } from 'next/server';

export async function GET() {
  const config = {
    clientId: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID,
    clientSecret: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET ? '***SET***' : '***NOT SET***',
    authEndpoint: SHOPIFY_CUSTOMER_ACCOUNT_AUTH_ENDPOINT,
    tokenEndpoint: SHOPIFY_CUSTOMER_ACCOUNT_TOKEN_ENDPOINT,
    logoutEndpoint: SHOPIFY_CUSTOMER_ACCOUNT_LOGOUT_ENDPOINT,
    redirectUri: SHOPIFY_CUSTOMER_ACCOUNT_REDIRECT_URI,
  };

  return NextResponse.json(config);
} 